language: python
cache: pip

addons:
    chrome: stable

python:
  - "3.6"

matrix:
  fast_finish: true

before_install:
  - sudo apt-get -qq update
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - wget https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$PWD

script:
  - pip install .
  - pip install .[tests]
  - pycodestyle dash_travis_testing tests
  - pytest tests
